---
# App deploy: king_detector and crane display. Run AFTER post-reboot-verify.yml passes.
- name: App Deploy (king_detector)
  hosts: localhost
  connection: local
  become: yes

  vars:
    deploy_user: lift
    user_home: "/home/{{ deploy_user }}"
    code_dir: "{{ user_home }}/code"
    repo_url: "git@github.com:davematthewsband/king_detector.git"
    repo_path: "{{ code_dir }}/king_detector"
    data_path: "{{ user_home }}/data"
    models_path: "{{ data_path }}/models"
    camera_static_start: 200
    timezone: "America/Chicago"
    ssh_port: 33412
    log_file: "/var/log/ansible-app-deploy-{{ ansible_date_time.iso8601_basic_short }}.log"

  tasks:
    # ==========================================================
    # 1. LOG INIT AND PROMPTS
    # ==========================================================
    - name: Initialize app-deploy log file
      shell: |
        echo "===========================================================" > {{ log_file }}
        echo "APP DEPLOY (king_detector) - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "" >> {{ log_file }}

    - debug:
        msg: "Starting app deploy - Log: {{ log_file }}"

    - name: Prompt for king_detector build version (branch)
      pause:
        prompt: |
          Which build version (branch) do you want to deploy?
          Type the branch or tag name (e.g. 2.9.0):
        echo: yes
      register: version_prompt

    - name: Set king_detector_version from prompt
      set_fact:
        king_detector_version: "{{ version_prompt.user_input | trim | default('2.9.0', true) }}"

    - name: Prompt for machine name (for .env and final instructions)
      pause:
        prompt: |
          Machine name for this install (e.g. Mars2):
        echo: yes
      register: machine_prompt

    - name: Set machine_name from prompt
      set_fact:
        machine_name: "{{ machine_prompt.user_input | trim | default('Mars2', true) }}"

    - name: Log prompts
      shell: |
        echo "Version: {{ king_detector_version }}" >> {{ log_file }}
        echo "Machine: {{ machine_name }}" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 2. PACKAGES (xdotool, x11-xserver-utils)
    # ==========================================================
    - name: Install xdotool and x11-xserver-utils
      apt:
        name:
          - xdotool
          - x11-xserver-utils
        state: present
        update_cache: yes

    - name: Log packages section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "2. PACKAGES - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "✅ xdotool, x11-xserver-utils installed" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 3. ETHERNET: CAMERA INTERFACES (static IPs)
    # ==========================================================
    - name: Get default route interface (has internet)
      shell: ip route show default 2>/dev/null | awk '{print $5}' | head -1
      register: default_route_iface
      changed_when: false
      failed_when: false

    - name: List UP ethernet interfaces (exclude lo)
      shell: |
        ip -br link show | awk '$2=="UP" && $1!="lo" {print $1}'
      register: up_interfaces_raw
      changed_when: false

    - name: Build list of camera interfaces (UP, no internet)
      shell: |
        default_if="{{ default_route_iface.stdout }}"
        for iface in {{ up_interfaces_raw.stdout_lines | default([]) | join(' ') }}; do
          [ -z "$iface" ] && continue
          [ "$iface" = "$default_if" ] && continue
          if ! ping -c 1 -W 2 -I "$iface" 8.8.8.8 >/dev/null 2>&1; then
            echo "$iface"
          fi
        done
      register: camera_ifaces_raw
      changed_when: false
      failed_when: false

    - name: Set camera_interfaces fact
      set_fact:
        camera_interfaces: "{{ camera_ifaces_raw.stdout_lines | default([]) | select('match', '^[a-zA-Z]') | list }}"

    - name: Build camera static config (name and address per interface)
      set_fact:
        camera_static_config: "{{ camera_static_config | default([]) + [{'name': item, 'address': '192.168.1.' ~ (camera_static_start + (camera_static_config | default([]) | length)) ~ '/24'}] }}"
      loop: "{{ camera_interfaces }}"
      when: camera_interfaces | length > 0
      loop_control:
        label: "{{ item }}"

    - name: Write netplan for camera interfaces only (99-camera-static.yaml)
      template:
        src: 99-camera-static.yaml.j2
        dest: /etc/netplan/99-camera-static.yaml
        mode: "0644"
      when: camera_static_config is defined and camera_static_config | length > 0

    - name: Apply netplan (camera static)
      command: netplan apply
      when: camera_static_config is defined and camera_static_config | length > 0

    - name: Log ethernet section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "3. ETHERNET (camera static) - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "Camera interfaces: {{ (camera_static_config | default([])) | map(attribute='name') | join(', ') | default('none') }}" >> {{ log_file }}
        {% for c in (camera_static_config | default([])) %}
        echo "  {{ c.name }}: {{ c.address }}" >> {{ log_file }}
        {% endfor %}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 4. CLONE king_detector (requested branch)
    # ==========================================================
    - name: Ensure code directory exists
      file:
        path: "{{ code_dir }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0755"

    - name: Clone king_detector (branch {{ king_detector_version }})
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ king_detector_version }}"
        force: no
        update: yes
      become_user: "{{ deploy_user }}"
      environment:
        HOME: "{{ user_home }}"
      when: not (ansible_check_mode | default(false))

    - name: Log clone section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "4. CLONE king_detector - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "Branch: {{ king_detector_version }}" >> {{ log_file }}
        echo "Path: {{ repo_path }}" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 5. CREATE .env FROM admin/env-file.md (dynamic)
    # ==========================================================
    - name: Check if admin/env-file.md exists in repo
      stat:
        path: "{{ repo_path }}/admin/env-file.md"
      register: env_file_md_stat

    - name: Read admin/env-file.md and create .env (replace mars2 etc with machine_name)
      block:
        - name: Slurp admin/env-file.md
          slurp:
            src: "{{ repo_path }}/admin/env-file.md"
          register: env_file_slurp

        - name: Decode and replace machine identifiers for .env
          set_fact:
            env_content: "{{ (env_file_slurp.content | b64decode).replace('mars2', machine_name).replace('Mars2', machine_name).replace('MARS2', machine_name | upper) }}"
          when: env_file_slurp.content is defined

        - name: Optionally replace MODEL_DIR path in .env content
          set_fact:
            env_content: "{{ env_content | regex_replace('MODEL_DIR=.*', 'MODEL_DIR=' ~ models_path) }}"
          when: env_content is defined and (env_content | length > 0) and ('MODEL_DIR=' in env_content)

        - name: Write .env to repo root
          copy:
            content: "{{ env_content }}"
            dest: "{{ repo_path }}/.env"
            owner: "{{ deploy_user }}"
            group: "{{ deploy_user }}"
            mode: "0600"
          when: env_content is defined and (env_content | length > 0)
      when: env_file_md_stat.stat.exists | default(false)

    - name: Create .env from fallback template when admin/env-file.md missing
      template:
        src: env_king_detector.j2
        dest: "{{ repo_path }}/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0600"
      when: not (env_file_md_stat.stat.exists | default(false))

    - name: Log .env section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "5. .ENV - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "Created from admin/env-file.md (machine_name={{ machine_name }})" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 6. DATA AND MODELS DIRECTORIES
    # ==========================================================
    - name: Ensure data and models directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: "0755"
      loop:
        - "{{ data_path }}"
        - "{{ models_path }}"

    - name: Log data/models section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "6. DATA/MODELS - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "{{ data_path }}, {{ models_path }}" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 7. VENV AND PIP (requirementsAutoUbuntu24cuda13.txt)
    # ==========================================================
    - name: Create Python venv in repo
      command: "python3 -m venv {{ repo_path }}/.venv"
      args:
        creates: "{{ repo_path }}/.venv/bin/python"
      become_user: "{{ deploy_user }}"
      environment:
        HOME: "{{ user_home }}"

    - name: Install pip requirements from file (requirementsAutoUbuntu24cuda13.txt)
      pip:
        requirements: "{{ repo_path }}/requirementsAutoUbuntu24cuda13.txt"
        virtualenv: "{{ repo_path }}/.venv"
        state: present
      become_user: "{{ deploy_user }}"
      environment:
        HOME: "{{ user_home }}"

    - name: Log venv section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "7. VENV/PIP - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "✅ venv and requirementsAutoUbuntu24cuda13.txt installed" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 8. CRANE DISPLAY AUTO-START (admin README)
    # ==========================================================
    - name: Make xinitrc-crane executable
      file:
        path: "{{ repo_path }}/admin/xinitrc-crane"
        mode: "0755"

    - name: Install crane-display-standalone.service (templated)
      template:
        src: crane-display-standalone.service.j2
        dest: /etc/systemd/system/crane-display-standalone.service
        mode: "0644"

    - name: Systemd daemon-reload and enable crane-display-standalone
      systemd:
        name: crane-display-standalone
        daemon_reload: yes
        enabled: yes
        state: stopped

    - name: Set default target to multi-user (no graphical login)
      command: systemctl set-default multi-user.target

    - name: Disable GDM
      systemd:
        name: gdm
        enabled: no

    - name: Log crane service section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "8. CRANE DISPLAY SERVICE - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "✅ crane-display-standalone enabled, GDM disabled" >> {{ log_file }}
        echo "" >> {{ log_file }}

    # ==========================================================
    # 9. TIMEZONE (America/Chicago)
    # ==========================================================
    - name: Set timezone to America/Chicago
      timezone:
        name: "{{ timezone }}"

    - name: Log timezone section
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "9. TIMEZONE - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "{{ timezone }}" >> {{ log_file }}
        echo "" >> {{ log_file }}

    - debug:
        msg: "If this machine is not in Houston/Central, set timezone manually: sudo timedatectl set-timezone <zone>"

    # ==========================================================
    # 10. FINAL MESSAGE AND MANUAL STEPS
    # ==========================================================
    - name: Log final summary
      shell: |
        echo "===========================================================" >> {{ log_file }}
        echo "APP DEPLOY SUMMARY - $(date)" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}
        echo "Version: {{ king_detector_version }}  Machine: {{ machine_name }}" >> {{ log_file }}
        echo "" >> {{ log_file }}
        echo "Manual steps:" >> {{ log_file }}
        echo "  1. Rsync models from your Mac to lift@{{ machine_name }}:~/data/models/" >> {{ log_file }}
        echo "  2. SSH forward camera and set camera time" >> {{ log_file }}
        echo "  3. Add host to ~/.ssh/config (e.g. Host {{ machine_name }})" >> {{ log_file }}
        echo "  4. Start crane: sudo systemctl start crane-display-standalone.service" >> {{ log_file }}
        echo "===========================================================" >> {{ log_file }}

    - name: Display final instructions
      debug:
        msg: |
          ✅ App deploy complete. Log: {{ log_file }}

          Manual steps (run from your Mac/laptop):

          1. Rsync models:
             rsync -avz --progress -e "ssh -p {{ ssh_port }}" /Volumes/shell/models/current/ lift@{{ machine_name }}:~/data/models/

          2. Camera time sync: forward camera over SSH, then set time in browser:
             ssh -p {{ ssh_port }} -L 8080:192.168.1.100:80 lift@{{ machine_name }}
             Then open http://localhost:8080 and set camera time to match computer.

          3. Add this host to ~/.ssh/config (e.g. Host {{ machine_name }}) so the above commands work.

          4. On the machine, start crane when ready:
             sudo systemctl start crane-display-standalone.service
             sudo journalctl -u crane-display-standalone -f
