#!/usr/bin/env bash
# Setup crane display machine: .env, venv, pip, xinit, systemd service, multi-user, GDM disabled.
# Run from king_detector repo root with sudo after automated_setup_2025 (ubuntu-setup + post-reboot-verify) has been run.
# Usage: sudo ./admin/setup-crane-machine.sh
#        MACHINE_NAME=Mars2 KING_DETECTOR_BRANCH=2.9.0 sudo -E ./admin/setup-crane-machine.sh

set -e

DEPLOY_USER="${DEPLOY_USER:-lift}"
USER_HOME="/home/${DEPLOY_USER}"
CODE_DIR="${USER_HOME}/code"
REPO_PATH="${CODE_DIR}/king_detector"
DATA_PATH="/data"
MODELS_PATH="${DATA_PATH}/models"
REPO_URL="${REPO_URL:-git@github.com:davematthewsband/king_detector.git}"

if [[ $EUID -ne 0 ]]; then
  echo "Run this script with sudo." >&2
  exit 1
fi

# Repo root: directory containing admin/ (when script is inside repo)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$SCRIPT_DIR" == */admin ]]; then
  REPO_ROOT="$(dirname "$SCRIPT_DIR")"
else
  REPO_ROOT=""
fi

# Use repo at REPO_PATH; if missing, clone to REPO_PATH
if [[ ! -d "$REPO_PATH" ]]; then
  echo "Repo not found at $REPO_PATH. Cloning..."
  BRANCH="${KING_DETECTOR_BRANCH:-2.9.0}"
  mkdir -p "$CODE_DIR"
  sudo -u "$DEPLOY_USER" git clone -b "$BRANCH" "$REPO_URL" "$REPO_PATH"
  echo "Cloned king_detector branch $BRANCH to $REPO_PATH"
fi
# When script is inside the repo at REPO_PATH, use it (SCRIPT_DIR is REPO_PATH/admin)
# When script is in a copy (e.g. drop-in folder), REPO_PATH is still the target path above

# Machine name for .env
if [[ -z "${MACHINE_NAME:-}" ]]; then
  read -r -p "Machine name (e.g. Mars2): " MACHINE_NAME
  MACHINE_NAME="${MACHINE_NAME:-Mars2}"
fi

# .env from admin/env-file.md or fallback
ENV_DEST="${REPO_PATH}/.env"
if [[ -f "${REPO_PATH}/admin/env-file.md" ]]; then
  ENV_CONTENT="$(sudo -u "$DEPLOY_USER" cat "${REPO_PATH}/admin/env-file.md")"
  ENV_CONTENT="${ENV_CONTENT//mars2/${MACHINE_NAME}}"
  ENV_CONTENT="${ENV_CONTENT//Mars2/${MACHINE_NAME}}"
  ENV_CONTENT="${ENV_CONTENT//MARS2/${MACHINE_NAME^^}}"
  if echo "$ENV_CONTENT" | grep -q 'MODEL_DIR='; then
    ENV_CONTENT="$(echo "$ENV_CONTENT" | sed "s|MODEL_DIR=.*|MODEL_DIR=${MODELS_PATH}|")"
  fi
  echo "$ENV_CONTENT" > "$ENV_DEST"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "$ENV_DEST"
  chmod 600 "$ENV_DEST"
  echo "Created .env from admin/env-file.md (machine=${MACHINE_NAME})"
else
  cat > "$ENV_DEST" << EOF
# Generated by setup-crane-machine.sh (fallback)
STATUS_MESSAGE=${MACHINE_NAME}
MODEL_DIR=${MODELS_PATH}
INFLUXDB_URL=http://localhost:8086
INFLUXDB_TOKEN=
INFLUXDB_ORG=
INFLUXDB_BUCKET=
PRIMARY_DETECTOR_GPU=cuda:0
SECONDARY_DETECTOR_GPU=cuda:1
EOF
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "$ENV_DEST"
  chmod 600 "$ENV_DEST"
  echo "Created .env from fallback template"
fi

# Directories
mkdir -p "$DATA_PATH" "$MODELS_PATH"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$DATA_PATH"
echo "Ensured $DATA_PATH and $MODELS_PATH"

# Venv and pip
if [[ ! -x "${REPO_PATH}/.venv/bin/python" ]]; then
  sudo -u "$DEPLOY_USER" python3 -m venv "${REPO_PATH}/.venv"
  echo "Created venv at ${REPO_PATH}/.venv"
fi
REQ_FILE="${REPO_PATH}/requirementsAutoUbuntu24cuda13.txt"
if [[ -f "$REQ_FILE" ]]; then
  sudo -u "$DEPLOY_USER" "${REPO_PATH}/.venv/bin/pip" install -r "$REQ_FILE"
  echo "Installed from requirementsAutoUbuntu24cuda13.txt"
fi
sudo -u "$DEPLOY_USER" "${REPO_PATH}/.venv/bin/pip" install "lap>=0.5.12"
echo "Ensured lap>=0.5.12"

# xinit
if ! command -v xinit &>/dev/null; then
  apt-get update -qq && apt-get install -y xinit
  echo "Installed xinit"
fi

# crane-display-standalone.service (repo admin/ or same dir as script)
SVC_SRC="${REPO_PATH}/admin/crane-display-standalone.service"
if [[ ! -f "$SVC_SRC" ]]; then
  SVC_SRC="${SCRIPT_DIR}/crane-display-standalone.service"
fi
if [[ ! -f "$SVC_SRC" ]]; then
  echo "Missing crane-display-standalone.service in repo admin/ or at ${SCRIPT_DIR}." >&2
  exit 1
fi
cp "$SVC_SRC" /etc/systemd/system/crane-display-standalone.service
chmod 644 /etc/systemd/system/crane-display-standalone.service
systemctl daemon-reload
systemctl enable crane-display-standalone.service
systemctl stop crane-display-standalone.service 2>/dev/null || true
echo "Installed and enabled crane-display-standalone.service (not started)"

# Boot and GDM
systemctl set-default multi-user.target
systemctl disable gdm 2>/dev/null || true
echo "Set default target to multi-user, disabled GDM"

# xinitrc-crane executable
if [[ -f "${REPO_PATH}/admin/xinitrc-crane" ]]; then
  chmod +x "${REPO_PATH}/admin/xinitrc-crane"
  echo "Made admin/xinitrc-crane executable"
fi

echo ""
echo "========== Setup complete =========="
echo ""
echo "Manual steps (run from your Mac/laptop):"
echo ""
echo "1. Rsync models:"
echo "   rsync -avz --progress -e \"ssh -p 33412\" /Volumes/shell/models/current/ ${DEPLOY_USER}@${MACHINE_NAME}:/data/models/"
echo ""
echo "2. Camera time sync: forward camera over SSH, then set time in browser:"
echo "   ssh -p 33412 -L 8080:192.168.1.100:80 ${DEPLOY_USER}@${MACHINE_NAME}"
echo "   Then open http://localhost:8080 and set camera time to match computer."
echo "   (Timezone was set by post-reboot-verify; ensure camera matches.)"
echo ""
echo "3. Add this host to ~/.ssh/config (e.g. Host ${MACHINE_NAME})."
echo ""
echo "4. On the machine, start crane when ready:"
echo "   sudo systemctl start crane-display-standalone.service"
echo "   sudo journalctl -u crane-display-standalone -f"
echo ""
